- Templates/Android/generated/BaseEntityRequest.java.tt
- Templates/Android/generated/BaseEntityRequestBuilder.java.tt
- Templates/Android/generated/IBaseEntityRequest.java.tt
- Templates/Android/generated/IBaseEntityRequestBuilder.java.tt
These changes modify the `Request` and `RequestBuilder` inheritance structure such that they no longer modeled after `Entity` hierarchies
> Removing inheritance hierarchy from Requests & RequestBuilders

- Templates/CSharp/Requests/EntityClient.cs.tt
- src/GraphODataTemplateWriter/.config/TemplateWriterSettings.json
- src/GraphODataTemplateWriter/Settings/TemplateWriterSettings.cs
The default base URL for a client is hard-coded in the template right now. Set it in config instead.
> Specify default base URL in config

- Templates/CSharp/Requests/IStreamRequestBuilder.cs.tt
- Templates/CSharp/Requests/StreamRequestBuilder.cs.tt
This is needed in order to add things like the nameConflictBehavior query param when building the request. Also, would allow adding custom headers, etc.
> Allow passing options collection to Request method for stream requests

- Templates/ObjC/Models/EnumType.m.tt
The enum is lowercase in the metadata and the enum definition. member.Name has the first character in upper case. This causes a build break.
> The first character of the enum should be lower case to match the schema

- Templates/ObjC/Base/SharedObjC.template.tt
- Templates/ObjC/Models/Models.h.tt
- src/GraphODataTemplateWriter/CodeHelpers/ObjC/TypeHelperObjC.cs
- Create the class 'MSTimeOfDay' to handle Edm.TimeOfDay. I will checkin this class to the ios graph sdk.
- For IsComplex(..), we should not do a Contains("int"). This results in incorrect return values for types that just have "int" in their names like 'timeConstraint' or 'interval'.
- For Duration & NSDictionary, return the types without appending.
> Introduce MSTimeOfDate for Edm.TimeOfDay and bug fixes

- Templates/ObjC/Base/SharedObjC.template.tt
- src/GraphODataTemplateWriter/CodeHelpers/ObjC/TypeHelperObjC.cs
- src/GraphODataTemplateWriter/Extensions/StringExtensions.cs
An OpenType is a property on ComplexType. If a ComplexType object is OpenType, the type is serialized as <Type>Collection. It should be a dictionary of <Type> if it exists. https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/checklistitemcollection has an example.
> Support for OpenType JSON objects.

- Templates/CSharp/Base/EntityRequest.Base.template.tt
- Templates/CSharp/Base/IEntityRequest.Base.template.tt
- Templates/CSharp/Base/SharedCSharp.template.tt
- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/CSharp/Model/EntityType.cs.tt
- Templates/CSharp/Model/EnumType.cs.tt
- Templates/CSharp/Model/MethodRequestBody.cs.tt
- Templates/CSharp/Requests/EntityCollectionResponse.cs.tt
- Templates/CSharp/Requests/EntityCollectionWithReferencesResponse.cs.tt
- Templates/CSharp/Requests/EntityRequest.cs.tt
- Templates/CSharp/Requests/IMethodRequest.cs.tt
- Templates/CSharp/Requests/MethodCollectionResponse.cs.tt
- Templates/CSharp/Requests/MethodRequest.cs.tt
- src/GraphODataTemplateWriter/.config/TemplateWriterSettings.json
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
[53036e5](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/53036e5bd49ec52a98821ec1be8ab0c99a2b7d38) - Turned on logging for template src, set default to config to .Net, and made change a change in OdcmModelExtensions, GetEntityReferenceTypes around filtering out reference collections. This last one has the great opportunity to impact generation and needs another set of eyes in case we see downstream impacts at generation.
[c7a70ec](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/c7a70eca601af2577eb8cdff6948e58816e35b7d) - Add overload to GetSanitizedPropertyName in case we generate a property name that collides with the name of the type.
6be8c55 - JsonProperty attribute, changed the Required property to FQN form to avoid collisions with property …
> Many changes, needs review

- src/GraphODataTemplateWriter/PathWriters/PHPPathWriter.cs
This fixes a manual change to conform to PSR-4. The class name must
match the file name
> Use sanitized property name

- Templates/CSharp/Model/ComplexType.cs.tt
Change the logic for when the [JsonConverter(typeof(DerivedTypeConverter))] attribute is applied on Complex Types to match the logic used for entities.
This resolves issue where an entity references an abstract complex type
> Add the DerivedTypeConverter to base class for Complex Types

- src/GraphODataTemplateWriter/.config/TypeScriptSettings.json
- src/GraphODataTemplateWriter/Settings/TemplateWriterSettings.cs
This enables us to generate and then copy-paste into the TS library. This also fixes a bug where DefaultFileCasing was not writeable.
> Update TS name to match library

- Templates/Java/models_generated/BaseEntity.java.tt
- src/GraphODataTemplateWriter/CodeHelpers/Java/CustomOverwrites.cs
Added the post processing method to the base model template and pulled in several overwrites for Planner functionality (see [https://github.com/microsoftgraph/msgraph-sdk-java/pull/34](https://github.com/microsoftgraph/msgraph-sdk-java/pull/34))
> Overwrites for Planner

- Templates/CSharp/Base/CollectionRequest.Base.template.tt
- Templates/CSharp/Base/EntityRequest.Base.template.tt
- Templates/CSharp/Base/ICollectionRequest.Base.template.tt
- Templates/CSharp/Requests/EntityCollectionPage.cs.tt
- Templates/CSharp/Requests/EntityCollectionRequest.cs.tt
- Templates/CSharp/Requests/IEntityCollectionPage.cs.tt
- Templates/CSharp/Requests/IEntityCollectionRequest.cs.tt
- Templates/CSharp/Requests/IStreamRequest.cs.tt
- Templates/CSharp/Requests/StreamRequest.cs.tt
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
In beta, there are two new "XYRequest" EntityType objects that require us to append "-Object" to the end (`fileClassificationRequest` and `textClassificationRequest`). These hit new scenarios in the templates that weren't previously checked, so this commit adds the appropriate checks in several more places.
There are probably other places in the templates where we are missing checks for `EndsWith("Request")` but it is a difficult piece to search for since the variable is not always consistently named. The best alternative would be to refactor this logic out of the individual templates.
> Acute fixes for RequestObject bugs

- Templates/CSharp/Base/ICollectionRequest.Base.template.tt
- Templates/CSharp/Base/IEntityRequest.Base.template.tt
- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/CSharp/Model/EntityType.cs.tt
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
Intellisense fixes to match https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/255
[0af305a](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/0af305a889790d3e48d647891bab904f41a826e8) - Added a long description sanitizer similar to Java that replaces invalid Intellisense characters with HTML equivalents
[d287f57](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/d287f57cc89a9bb41b89589d1895931b37869f78) - Cancellation token comment was being generated randomly at the top of the document instead of in line with the rest of the method comment
> Intellisense fixes for .NET

- Templates/Android/generated/BaseEntityWithReferenceRequest.java.tt
- Templates/Android/generated/IBaseEntityWithReferenceRequest.java.tt
- Templates/CSharp/Base/EntityRequest.Base.template.tt
- Templates/CSharp/Requests/EntityWithReferenceRequest.cs.tt
- Templates/CSharp/Requests/IEntityWithReferenceRequest.cs.tt
- Templates/Java/requests_generated/BaseEntityWithReferenceRequest.java.tt
- Templates/Java/requests_generated/IBaseEntityWithReferenceRequest.java.tt
For C#/Java/Android, the libraries are missing delete, post, and/or patch.
Some scenarios allow users to delete/update references to items (these all seem to be on the directoryObject item). Two examples are DELETE on group member and DELETE on directory role member.
> Add DELETE/POST/PATCH to (I)EntityWithReferenceRequest

- Templates/CSharp/Requests/IEntityWithReferenceRequest.cs.tt
- src/GraphODataTemplateWriter/.config/TemplateWriterSettings.json
Fixes issue introduced with #131 
Was causing the following issue at generation time.
```
11:25:29 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(0): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityWithReferenceRequest.cs.tt(22,64) : error CS1501: No overload for method 'GetEntityGetAsyncMethod' takes 2 arguments
11:25:30 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(1): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityWithReferenceRequest.cs.tt(24,64) : error CS1501: No overload for method 'GetEntityCreateAsyncMethod' takes 2 arguments
11:25:30 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(2): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\ …
```
> Fix with ref request

- Templates/Java/BaseJavaModel.template.tt
- Templates/Java/requests_generated/BaseMethodBodyRequest.java.tt
- Templates/Java/requests_generated/IBaseMethodBodyRequest.java.tt
Fixing import statements for BaseMethodBodyRequest template
Fixing import statements for IBaseMethodBodyRequest template
Together these templates impact ~800 files and these files will start getting optimized import statements with this fix.
Testing:
After generating files using these templates, java sdk has started building with 3GB RAM.
> Java template fix to reduce memory footprint - continued

- Templates/Java/requests_generated/BaseMethodCollectionRequestBuilder.java.tt
I have put a check for null values of function/action parameters in BaseMethodCollectionRequestBuilder template for Java.
It will stop passing null valued parameters to requests which are generated through this template.
> A check for null values of function/action parameters

- GraphODataTemplateWriter.sln
- Templates/CSharp/Base/CollectionRequest.Base.template.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
This change adds support for NavigationPropertyBindings for singletons as a generation hint for generating the correct canonical URLs for adding references to non-contained navigation entities. 
The education based files represent the outcome of this change.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/afterNavPathUpdate
> Support nav path bindings

- Templates/Java/BaseJavaModel.template.tt
Changes in base java template file to remove duplicate import statments when same property is used multiple times within a file.
Fix is to use a dictionary to keep track of import statement and skip if identical import statement is encountered again.
[BaseUser_BeforeAfterChanges.zip](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/files/2389200/BaseUser_BeforeAfterChanges.zip)
> Remove duplicate import statemement

- Templates/TypeScript/src/entity_types.ts.tt
**Sharepoint issue:** In particular the Entity type’s id and the createdDateTime and lastModifiedDateTime fields are now not nullable.  This makes list creation in SharePoint problematic since those fields are server generated and shouldn’t be expected when you’re doing a POST to create a list or Column Definition (both of which derive from those base types).
Potentially a blocker for web part demo for Ignite. so reverting the strict model types generation.
> Revert strict model generation for typescript

- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/PHP/Model/ComplexType.php.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
@odata.type property is now serialized for all complexTypes. We need to:
This will fix https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/294.
This will be applicable for .Net, Java, PHP, and TypeScript.
I'll link to what this looks like in a .Net PR.
> Add odata type to complex types for .Net and PHP

- Typewriter.nuspec
- src/Typewriter/Properties/AssemblyInfo.cs
Typewriter package version will be based on assemblyversion.
> Fixed copyright, made assembly semver

- scripts/CreateChocoPackage.ps1
The existing script in the build task didn't do its job. This script reads the latest published package version and updates the new package version based on assembly version and/or the last published version.
> Choco pack and versioning script made more robust

- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/CSharp/Model/EntityType.cs.tt
GetSanitizedLongDescription captures both Description and LongDescription. We were missing many descriptions when we weren't checking the Description property.
This issue also exists for:
- TypeScript
- PHP
- Probably Java
> Capture more descriptions.

- README.md
- src/Typewriter/DocAnnotationWriter.cs
- src/Typewriter/FileWriter.cs
- src/Typewriter/Generator.cs
- src/Typewriter/Options.cs
- src/Typewriter/Program.cs
- src/Typewriter/Typewriter.csproj
- test/Typewriter.Test/GeneratorTests.cs
- test/Typewriter.Test/MetadataPreprocessorTests.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
- test/Typewriter.Test/Typewriter.Test.csproj
This allows us to use typewriter in different ways in our build pipeline. There are now three generation options:
* Clean, annotate, and generate output metadata from an input metadata file.
* Generate code files from arbitrary input metadata without cleaning or annotating the metadata.
* Clean and annotate an input metadata before generating code files.
> Add generation options

- src/Typewriter/Typewriter.csproj
Incorp https://github.com/OneDrive/apidoctor/pull/9
Fixes issue where ApiDoctor built with JSON.Net 6 but NuGet pulls in JSON.Net 7.
> Update apidoctor reference

- Templates/PHP/Model/ComplexType.php.tt
- Templates/PHP/Model/EntityType.php.tt
- src/GraphODataTemplateWriter/CodeHelpers/PHP/TypeHelperPHP.cs
Added support for both description and long description as well sanitizing description strings.
MarkdownScanner to ApiDoctor appeared to change the way doc comments are parsed into the object model. This change addresses that change in the templates.
This will address the issue of the missing descriptions in https://github.com/microsoftgraph/msgraph-sdk-php/pull/116
> Use both description and long description annotations

- Templates/Java/BaseJavaModel.template.tt
Added support for both description and long description as well sanitizing description strings.
MarkdownScanner to ApiDoctor appeared to change the way doc comments are parsed into the object model. This change addresses that change in the templates. Want to make sure that we don't miss descriptions. 
I branched this from dev. One thing I didn't understand is why did I generate with the import * everything declarations instead of what I see checked into the repo. Is there a branch that needs to be pulled into dev that you've been using for generation?
> Use description and long description annotations for Java

- Templates/TypeScript/src/entity_types.ts.tt
- src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeHelperTypeScript.cs
Added support for both description and long description as well sanitizing description strings.
MarkdownScanner to ApiDoctor appeared to change the way doc comments are parsed into the object model. This change addresses that change in the templates.
This will add many more jsdoc comments.
> Use description and long description annotations for TS

- Templates/Java/BaseJavaModel.template.tt
Fixing import statements for request builder classes when an enumset property gets used in the class.
[BaseTeamCloneRequestBuilder.zip](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/files/2679316/BaseTeamCloneRequestBuilder.zip)
> Fixing import statement for java sdk

- Templates/CSharp/Requests/IMethodRequest.cs.tt
- Templates/CSharp/Requests/MethodRequest.cs.tt
When generating the SDK, certain parameter names were not being sanitized, which resulted in errors such as myfunc(string string), as opposed to myfunc(string @string). To fix this, I sanitized the parameter .
> Sanitize Parameter variables to fix errors

- GraphODataTemplateWriter.Test/GraphODataTemplateWriter.Test.csproj
- Templates/CSharp/Base/EntityRequestBuilder.Base.template.tt
- Templates/CSharp/Base/IEntityRequestBuilder.Base.template.tt
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
Fixes build errors brought about due to template file instantiating property to have same name as methods within the same class. The commits within this PR perform a specific check to ensure this does not happen, allowing successful build.
> Fix build errors for same method and property name

- README.md
- Templates/PHP/Model/ComplexType.php.tt
- Templates/PHP/Model/EntityType.php.tt
- Templates/PHP/Model/EnumType.php.tt
- src/GraphODataTemplateWriter/Settings/ConfigurationService.cs
- src/GraphODataTemplateWriter/Settings/TemplateWriterSettings.cs
- src/GraphODataTemplateWriter/TemplateProcessor/TemplateProcessor.cs
- src/GraphODataTemplateWriter/TemplateProcessor/TemplateWriter.cs
- src/Typewriter/Generator.cs
- src/Typewriter/Options.cs
- test/Typewriter.Test/GeneratorTests.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_metadata_preprocessor.cs
- test/Typewriter.Test/MetadataPreprocessorTests.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
- test/Typewriter.Test/Typewriter.Test.csproj
Typewriter can now support properties to be specified from the CLI and used in the templates. This option should only be used when:
* We can't update target metadata either by having workload teams fix their metadata, or by alteration with the metadata preprocessor.
* We can't make a fix in the templates or template logic by themselves.
* We need to inject control data at runtime.
The specified properties can be accessed from the templates. We needed this for beta PHP file generation since it uses a different namespace.
The attached file demonstrates the file generated from the test case where it injects a custom namespace.
[Entity.txt](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/files/2819516/Entity.txt)
* Updated the readme with information on the new command line …
> Add support for specifying properties from the typewriter cli

- src/GraphODataTemplateWriter/Settings/ConfigurationService.cs
- src/GraphODataTemplateWriter/TemplateProcessor/TemplateWriter.cs
- src/Typewriter/Generator.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
Via the endpointVersion argument.
This change will affect the following templates:
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/Templates/CSharp/Requests/EntityClient.cs.tt#L25
> Support updating the default base Graph URL

- src/GraphODataTemplateWriter/.config/ObjCSettings.json
- src/GraphODataTemplateWriter/Settings/ConfigurationService.cs
- src/GraphODataTemplateWriter/TemplateProcessor/TemplateWriter.cs
- src/Typewriter/Generator.cs
- src/Typewriter/MetadataPreprocessor.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
Adding containment navigation to enable beta generation.
> Added intune preprocessing

- GraphODataTemplateWriter.Test/TypeHelperTests.cs
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
- src/GraphODataTemplateWriter/CodeHelpers/PHP/TypeHelperPHP.cs
- src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeHelperTypeScript.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
Fixes #187 
HTML encoded CRLF in doc annotations gets converted to escaped chars \r\n. We need to make sure we emit the new line doc comments with ///. Updated C#, PHP, and Typescript to support this.
> Handle CRLF in doc annotations as code comments.

- Templates/CSharp/Base/IRequestBuilder.Base.template.tt
today:
```cs
interface ICallParticipantsCollectionRequestBuilder
{
}
```
proposed change:
```cs
interface ICallParticipantsCollectionRequestBuilder : IBaseRequestBuilder
{
}
```
As far as I can tell, the method altered (`GetInterfaceDefinition`) is only reference by the following templates:
```cs
ICollectionRequestBuilder.Base.template.tt:
public string GetCollectionInterfaceDefinition(OdcmProperty odcmProperty);
public string GetCollectionReferencesInterfaceDefinition(OdcmProperty odcmProperty);
public string GetCollectionWithReferencesInterfaceDefinition(OdcmProperty odcmProperty);
IEntityRequestBuilder.Base.template.tt:
public string GetEntityReferenceRequestBuilderInterfaceDefinition(OdcmClass odcmClass);
public string GetEntityWithReferenceRequestBuilderInterfaceDefinition(OdcmClass …
```
> Changing I<*>RequestBuilder : IBaseRequestBuilder

- Templates/PHP/Model/EnumType.php.tt
- src/GraphODataTemplateWriter/Extensions/StringExtensions.cs
This change only impacts 2 entities in beta. It basically makes the underscoring rule also be applicable to existing underscores. This fix unblocks beta generation for PHP. This fixes [PHP#167](https://github.com/microsoftgraph/msgraph-sdk-php/issues/167).
This change fixes the generation scenario where two different member names are similar by having camelcase with preceding underscores like this:
<Member Name="remoteControlSoftware" Value="25" />
<Member Name="remote_Control_Software" Value="33" />
The above member names *were* both being generated as REMOTE_CONTROL_SOFTWARE. This fix differentiates the two as seen in image 1. Image 2 shows the other enum affected by this template change.
**Image 1. Change made to WindowsMalwareCategory.php by this change. This is the target that is …
> Fix for enum naming for camelcased+underscore scenario

- src/Typewriter/MetadataPreprocessor.cs
This PR fixes broken beta build by setting`ContainsTarget="true"` to indicate containment for new Intune entities.
> Add contains target for new Intune entities.

- Templates/CSharp/Model/EntityType.cs.tt
- src/Typewriter/MetadataPreprocessor.cs
This is related to 9850b8342e0d7649ab4a6ae69ce197dc2f0dd2a6
Fixes #212
When running this against https://github.com/microsoftgraph/msgraph-metadata/blob/a59f43e83cda8f097d7a5e6dd71516438fcb2267/beta_metadata.xml with the generator before and after changes, we see the changes in the following files:
* ScheduleChangeRequest.cs
* ShiftChangeRequest.cs
* SwapShiftsChangeRequest.cs
* TimeOffRequest.cs
The following example shows the potential changes made by this update:
@bilalgce This may have implications for Java.
> Disambiguation for base and cstor on EntityType

- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/CSharp/Model/EntityType.cs.tt
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
**modified:   Templates/CSharp/Model/ComplexType.cs.tt**
Add public cstor and ODataType initialization for
non-abstract complextypes.
**modified:   Templates/CSharp/Model/EntityType.cs.tt**
Add public cstor and ODataType initialization for
non-abstract entitytypes.
modified:   test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
modified:   test/Typewriter.Test/Resources/dirtyMetadata.xml
Address:
Fixes microsoftgraph/msgraph-sdk-dotnet-core#36
Examples:
> Init OData.Type on complex and entity types.

- Templates/CSharp/Requests/EntityClient.cs.tt
This PR modifies the template for the GraphServiceClient to add a new constructor to add support for the following scenario
```
HttpClient client = GraphClientFactory.Create(...);
var graphServiceClient = new GraphServiceClient(client);
```
This PR is related to 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/38 (predecessor) 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/27
> Adds constructor to GraphServiceClient template

- src/Typewriter/MetadataDefinitionType.cs
- src/Typewriter/MetadataPreprocessor.cs
- src/Typewriter/Options.cs
- src/Typewriter/Typewriter.csproj
- test/Typewriter.Test/Given_a_valid_metadata_file_to_metadata_preprocessor.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
Fixes #222.
Enables us to reorder elements in any global metadata element.
> Add element reorder capability

- Templates/CSharp/Base/IRequestBuilder.Base.template.tt
- Templates/CSharp/Base/RequestBuilder.Base.template.tt
- Templates/CSharp/Model/ComplexType.cs.tt
- Templates/CSharp/Model/EntityType.cs.tt
- Templates/CSharp/Requests/MethodRequestBuilder.cs.tt
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
Unblocks beta generation issues.
A model class generated from a complex type can result in a naming collision with a request builder.
Since there is a Search entity, a SearchRequest object is generated as a request object, and SearchRequest object is generated for the models.
Overloads aren't differentiated by binding element if the binding element is an entity or a collection of entities of the same type. 
This fixes a hacky fix used to disable duplicate cstors for SynchronizationJobValidateCredentialsRequestBuilder. 
For this content
We now properly generate this:
> Disambiguate complex type, better method overload support

- Templates/CSharp/Base/IRequestBuilder.Base.template.tt
- Templates/CSharp/Base/RequestBuilder.Base.template.tt
- Templates/CSharp/Model/MethodRequestBody.cs.tt
ComplexTypes ending with 'Request' are disambiguated by appending
'Object' to their name. We need to support this for optional Action
and Function arguments.
modified:   Templates/CSharp/Base/IRequestBuilder.Base.template.tt
modified:   Templates/CSharp/Base/RequestBuilder.Base.template.tt
modified:   Templates/CSharp/Model/MethodRequestBody.cs.tt
This change was used to generate the beta update, but was not added to the PR.
> Support disambiguated objects for OData MethodRequestBody

- README.md
- src/Typewriter/Generator.cs
- src/Typewriter/Options.cs
- src/Typewriter/Program.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
This PR applies the specified XSLT to a metadata file which results in the transformed file. Optional doc annotations can be added to the metadata output file.
Checkout out this branch, build typewriter.sln.
Try running this:
`.\typewriter.exe -v Info -m https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/v1.0_metadata.xml -g Transform -t https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/transforms/csdl/preprocess_csdl.xsl -o transformOutput`
You should see most of these rules applied to the output CSDL.
https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/transforms/csdl/preprocess_csdl.xsl
> Support XSLT based cleaning of CSDL metadata

- .nuget/nuget.config
- GraphODataTemplateWriter.Test/TypeHelperTests.cs
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
When namespaces contained already PascalCased tokens, such as 'Microsoft.OfficeShared.Etc', the namespace generation would convert the namespace to 'Microsoft.Office Shared.Etc'.
This PR simply removes the whitespace that Inflector's Titleize method adds to the namespace.
Using Inflector's Pascalize method doesn't work due to the regex used not recognizing the '.' character as a token delimiter.
> Removed whitespace being generated by Inflector library on namespaces

- Templates/Java/BaseJavaModel.template.tt
- Templates/Java/requests_extensions/BaseMethodCollectionResponse.java.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
The changes in this PR affect the following files:
The files marked in blue are changed but aren't affected by the change. They now have an additional unused import (there are many, and represent a different set of challenges). We could add a template exclusion list to the code, but that does not feel right.
The change in  BaseMethodCollectionResponse .java.tt results in us not generating setters for instance annotations for enum return types; because enum values don't have instance annotations. This only impacts the generated CalendarAllowedCalendarSharingRolesCollectionResponse.java.
The metadata has entities named timeOff and timeOffRequest. The entity named timeOff results in us generating files named models.timeOff and requests.timeOffRequest. The entity named timeOffRequest results …
> Fix Java generation - support methods that return enums, disambiguate entities that end in "Request"

- Templates/PHP/Model/ComplexType.php.tt
Fixed an issue where PHP models for complex types would not refer to built-in PHP types as expected. For example, without this, these models would be referring to an inexistent `Microsoft\Graph\Model\\DateTime` class, instead of PHP's `\DateTime` class.
See https://github.com/microsoftgraph/msgraph-sdk-php/pull/231.
> Check whether this type is a generated model type or a PHP type

- Templates/TypeScript/src/entity_types.ts.tt
These values are used by DefinatelyTyped for accepting and signing off PRs.
> Set typescript owners in template

- Templates/TypeScript/src/entity_types.ts.tt
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/257
> Add Option type for NULL fields

- Templates/TypeScript/src/entity_types.ts.tt
> Removing the Type Definition header from the TypeScript Template

- Templates/TypeScript/src/entity_types.ts.tt
- src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeScriptNamespace.cs
- test/Typewriter.Test/TestDataTypeScript/com/microsoft/graph/src/Microsoft-graph.d.ts
This is fixing the issues found by `dtslint`. (thanks @nikithauc).
1. Double empty lines are removed.
2. `export` in subnamespace types are removed as they are not needed.
Code diff can be seen in the test changes.
`.\Typewriter.exe -v Info -m 'https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml' -o .\TypeScriptLintFixesV1\ -g Files -l TypeScript`
`.\Typewriter.exe -v Info -m 'https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml' -o .\TypeScriptLintFixesBeta\ -g Files -l TypeScript`
[AB#5029](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5029)
> Fix linting errors in TypeScript namespace generation

- Templates/Java/requests_extensions/BaseEntityCollectionRequest.java.tt
- Templates/Java/requests_extensions/IBaseEntityCollectionRequest.java.tt
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/CallCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/EntityType2CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/EntityType3CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/ICallCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/IEntityType2CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/IEntityType3CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/ITimeOffCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/ITimeOffRequestCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/TimeOffCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/TimeOffRequestCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/CallRecordCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/ICallRecordCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/ISegmentCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/ISessionCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/SegmentCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/SessionCollectionRequest.java
entity collection requests in java were missing extension methods to allow consumers to provide the skip and skipToken arguments.
https://github.com/microsoftgraph/msgraph-sdk-java/pull/443
> - adds missing skip and skipToken methods for collection requests

- Templates/Java/requests_extensions/BaseEntityCollectionReferenceRequest.java.tt
- Templates/Java/requests_extensions/BaseEntityCollectionRequest.java.tt
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/CallCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/EntityType2CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/EntityType3CollectionReferenceRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/EntityType3CollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/TimeOffCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/extensions/TimeOffRequestCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/CallRecordCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/SegmentCollectionRequest.java
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/extensions/SessionCollectionRequest.java
Because getRequestUrl already inserts the options (functions and query), providing the options again in build request was inserting those twice, causing the request to fail.
https://github.com/microsoftgraph/msgraph-sdk-java/pull/445
> - fixes a bug where url options would be inserted twice for collection POST requests

- Templates/CSharp/Model/MethodRequestBody.cs.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
CSDL reordering triggered this regression. Discovered that reordered overloaded action, evaluateDynamicMembership was missing a property. We were only capturing parameters for the first overload. We need to capture all of the parameters which this commit fixes.
> Supports missing request body parameter

- Templates/CSharp/Base/SharedCSharp.template.tt
- Templates/CSharp/Requests/IMethodRequest.cs.tt
- Templates/CSharp/Requests/MethodRequest.cs.tt
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
ODate primitives method return types are returned in an object.
We weren't handling the object which resulted in serialization
exceptions.
modified:   Templates/CSharp/Base/SharedCSharp.template.tt
modified:   Templates/CSharp/Requests/MethodRequest.cs.tt
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/160
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/800
```pwsh
-v Info -m https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml -o dotnetbeta_old -l CSharp -g Files -e beta
-v Info -m https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml -o dotnetbeta_new -l CSharp -g Files -e beta
```
The generated changes are …
> Fix OData methods with OData primitive return type

- Templates/CSharp/Base/SharedCSharp.template.tt
- Templates/CSharp/Requests/IMethodRequest.cs.tt
- Templates/CSharp/Requests/MethodRequest.cs.tt
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/Resources/dirtyMetadata.xml
ODate primitives method return types are returned in an object.
We weren't handling the object which resulted in serialization
exceptions.
modified:   Templates/CSharp/Base/SharedCSharp.template.tt
modified:   Templates/CSharp/Requests/MethodRequest.cs.tt
modified:   Templates/CSharp/Requests/IMethodRequest.cs.tt
> Release: Fix OData methods with OData primitive return type (#300)

- src/GraphODataTemplateWriter/GraphODataTemplateWriter.csproj
MonTextTemplate ships multiple tarets with version 2.0.5 which changes the path of the DLL.
During the last update, dependabot didn't update the path causing a broken hint path.
This fixes the reference path, until we move to dotnet core and package references.
> - fixes an issue where the dependabot reference didn't update the assembly path following upgrade

- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
- src/GraphODataTemplateWriter/CodeHelpers/PHP/TypeHelperPHP.cs
- src/GraphODataTemplateWriter/Extensions/StringExtensions.cs
- src/GraphODataTemplateWriter/GraphODataTemplateWriter.csproj
inflector hasn't been upgraded to dotnet standard. However the community put together a fork on dotnet standard that's more popular than the original thing.
> - replaces inflector by its dotnet standard verssion

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- scripts/run-typewriter-clean-metadata.ps1
This change is needed so that we can support adding documentation to the beta clean metadata.
https://github.com/microsoftgraph/msgraph-metadata/pull/46
> Add endpoint for runs of typewriter when adding docs

- src/GraphODataTemplateWriter/.config/CSharpSettings.json
Having duplicate entries in the template mapping was causing us to write the same files twice or thrice.
This saves us time by having 1516 less file writes out of 10853 in V1 (around 14%).
I have compared the latest V1 output and they match exactly for c#.
> [Perf] Remove duplicate template mappings to avoid generating the same files

- Templates/templates/CSharp/Requests/EntityCollectionWithReferencesRequest.cs.tt
Fixes a bug where the class block is closed only if Sortable is true. Moved the closing curly bracket outside the condition.
This was blocking the generation if we keep the capability annotations from metadata.
> Close class block unconditionally

- Templates/templates/CSharp/Base/ICollectionRequest.Base.template.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/IGroupMembersCollectionReferencesRequest.cs
Fixes #406
This blocks generating AddAsync for a collection reference request, if we can't find the non-contained collection either as a top level entity set or as a contained navigation property of a top level singleton.
I have also considered the option of adding it regardless without checking the condition, because reference request doesn't make sense without AddAsync, but that requires us to resolve where the navigation property is located for building its name. (cc: @ddyett)
I have compared current V1 and Beta outputs for C# and they match exactly with and without the change.
That is expected because when the condition for inconsistency occurs, it causes a build failure. So we used to remove those inconsistencies by XSLT.
@MIchaelMainer, this should unblock current Beta generation …
> Make class and interface generation consistent

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/checkout-metadata.yml
- .azure-pipelines/generation-templates/language-generation.yml
- scripts/git-push-cleanmetadata.ps1
- src/Typewriter/DocAnnotationWriter.cs
- src/Typewriter/Generator.cs
This PR includes the following fixes:
- Curly apostrophe was showing up as ? because ASCII encoding of the XML (e.g. `Defender’s actions` was showing up as `Defender?s actions`). Changed encoding to UTF8.
- The fix replacing curly apostrophe with regular: https://github.com/microsoftgraph/microsoft-graph-docs/pull/11538. It is blocked because the text in question is auto generated.
- Checking in metadata changes are now optional for testing purposes (repurposed publishChanges parameter)
- Added a step into metadata cleaning pipeline to publish generated metadata as an artifact for debugging purposes.
- Docs have a lot of empty base type explicitly defined as empty strings. Those empty strings were showing up as base types in the clean metadata which was blocking the OpenAPI conversion. …
> Unblock beta generation

- .azure-pipelines/generation-pipeline.yml
- .github/workflows/dotnet.yml
Fixes #429 
- Updates the schedule to use `main`
- Updates the PR checks to use `main`
> Update schedule, rename master to main

- .azure-pipelines/generation-pipeline.yml
Fixes #441 per https://stackoverflow.com/questions/56756536/scheduled-builds-never-trigger-in-azure-devops-pipeline
> Change cron definition in YAML to single quote

- test/Typewriter.Test/MultipleNamespacesTestRunner.cs
Fixes #444
This adds an early file count check to make sure that generated file count matches with expected. Previously we were not testing for newly generated files because we were only walking the expected file tree and checking whether those files appear in the actual output. This was missing new additions to the actual output.
I have tested with latest code, this condition passes.
I have also cherry-picked the same changes and applied into an earlier state of the repo where there was a mismatch and the condition failed there.
> Fix file comparison condition where there are new files

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/language-generation.yml
- .azure-pipelines/generation-templates/set-up-for-generation.yml
- scripts/git-push-cleanmetadata.ps1
- scripts/git-push-files.ps1
Fixes #450 by using metadata as an artifact instead of checking out the metadata repo in an earlier snapshot.
In the case that "skip metadata clean and capture" is set, the pipeline continues to use `msgraph-metadata` repo directly. If it is not set, it downloads the uploaded artifact from the build.
I used the same folder structure between explicit checkout vs downloading from artifact to simplify file path inputs to typewriter.
Fixes #454 by using `-eq` with environment variable checks because they are strings by default and there is an implicit type conversion even if assigned value is boolean.
I ran the full pipeline with "skip metadata clean and capture" not set and set. There is no difference generated in the subsequent run.
Diffs: …
> Fix generation pipeline stages

- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/CallRecordItemRequestBuilder.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/ICallRecordItemRequestBuilder.cs
- Unblocks beta generation in staging.
- Fixes #492
- Successful build with the change: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=44362&view=ms.vss-test-web.build-test-results-tab
It turns out we already had a case in the test data but fully qualified name was missed in the PRs (I only changed the test output data in this PR to the expected fully qualified name). Maybe we should consider adding a compilation test to the test data in the corresponding .NET repo (#494). This was what I was doing in local dev environment while developing the namespaces feature.
> MethodRequestBuilders to use fully qualified name for cross namespace references

- Templates/templates/CSharp/Requests/EntityClient.cs.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/GraphServiceClient.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/916.
It enables the users of the SDK to define their own base address for the request builders in the event they are using their own httpclient and varying clouds.
Generation PRs:
V1 - https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/959
Beta - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/276
> Adds ability to override the base url in httpclient constructor

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
PHPDocs of some setters set the return to a wrong class in the PHPDoc. This happens mostly when the class is also an inbuilt PHP type prefixed with `Graph`.
N/A
Closes #521
[#493](https://github.com/microsoftgraph/msgraph-sdk-php/pull/493)
[#492](https://github.com/microsoftgraph/msgraph-sdk-php/pull/492)
> Fix type issues in PHPDocs.

- Templates/templates/CSharp/Requests/EntityClient.cs.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/GraphServiceClient.cs
This PR makes the properties of GraphServiceClient virtual to enable the use of mocking frameworks such as Moq to be able to override the implementations provided in the class after the dropping of the IGraphServiceClient interface.
V1 generation
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1040
beta generation
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/312
> Make properties of GraphServiceClient virtual

- Templates/templates/PHP/Model/ComplexType.php.tt
- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/OnenotePage.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/OnenotePage.php
Replaces references to the deprecated function `GuzzleHttp\Psr7\stream_for()` with `GuzzleHttp\Psr7\Utils::streamFor()`
All the occurrences of `GuzzleHttp\Psr7\stream_for()` are now replaced with `GuzzleHttp\Psr7\Utils::streamFor()`
N/A
[#543](https://github.com/microsoftgraph/msgraph-sdk-php/issues/543)
> Replace `GuzzleHttp\Psr7\stream_for()` with `GuzzleHttp\Psr7\Utils::streamFor()`

- Templates/templates/PHP/Model/ComplexType.php.tt
- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
- Fixes the issue with missing key check before actually trying to get the key from the property dictionary for the `getODataType()` method.
- Fixes the issue with missing parameter for ctor in some classes which are actually called passing an argument.
N/A
Issue [#287](https://github.com/microsoftgraph/msgraph-sdk-php/issues/287)
PR [#539](https://github.com/microsoftgraph/msgraph-sdk-php/pull/539)
> Fix the constructor called with no parameters add key-check for `getODataType()`

- Templates/templates/Java/requests/BaseEntityRequestBuilder.java.tt
- Templates/templates/Java/requests/BaseEntityStreamRequestBuilder.java.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
adds missing content methods for request builders of types that inherit types with has stream=true.
additional context https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/128
beta diff https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/130
v1 diff https://github.com/microsoftgraph/msgraph-sdk-java/pull/820
> adds missing inherited content methods for java

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/php-v1.yml
The `v1.0` model generation for PHP is failing due an issue with PATH that I introduced in a #554.
N/A
N/A
Closes #559
> Fix failing generation of v1.0 models for PHP

- Templates/templates/CSharp/Model/EnumType.cs.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/Enum1.cs
This PR implements a fix for the EnumType template where the `using System;` statement is needed in the event that the type is deprecated in order to prevent compilation issues with the [ObsoleteAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=net-5.0) that could be potentially added to the class.
> Include missing using statement in enum types

- Templates/templates/PHP/Model/ComplexType.php.tt
- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/OnenotePage.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/OnenotePage.php
Reverts microsoftgraph/MSGraph-SDK-Code-Generator#555 to maintain backward compatibility.
Change will be valid after we do a major upgrade of the SDK.
More info https://github.com/microsoftgraph/msgraph-sdk-php/pull/561
Fixes https://github.com/microsoftgraph/msgraph-sdk-php/issues/560
> Revert "Replace `GuzzleHttp\Psr7\stream_for()` with `GuzzleHttp\Psr7\Utils::streamFor()`"

- Templates/templates/PHP/Model/ComplexType.php.tt
- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/OnenotePage.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/OnenotePage.php
Reverts microsoftgraph/MSGraph-SDK-Code-Generator#567
After further discussion with the PHP team, we'll be moving forward with this change that I had previously reverted.
@MIchaelMainer @SilasKenneth @roinochieng 
Linking to https://github.com/microsoftgraph/msgraph-sdk-php/issues/560
> Returns "Replace `GuzzleHttp\Psr7\stream_for()` with `GuzzleHttp\Psr7\Utils::streamFor()`""

- Templates/templates/CSharp/Model/EntityType.cs.tt
- Templates/templates/CSharp/Requests/EntityCollectionResponse.cs.tt
- Templates/templates/CSharp/Requests/EntityCollectionWithReferencesResponse.cs.tt
- Templates/templates/CSharp/Requests/MethodCollectionResponse.cs.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/CloudCommunications.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/Group.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/Schedule.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/CloudCommunicationsCallRecordsCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/CloudCommunicationsCallsCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/GraphServiceTestTypesCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/GroupMembersCollectionWithReferencesResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/ScheduleTimeOffRequestsCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/ScheduleTimesOffCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/TestTypeQueryCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/UnifiedRoleEligibilityRequestFilterByCurrentUserCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/model/CallRecord.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/model/Segment.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/model/Session.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/CallRecordRecipientsCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/CallRecordSessionsCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/SegmentRefTypesCollectionWithReferencesResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/SegmentTestActionCollectionResponse.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/SessionSegmentsCollectionResponse.cs
This PR is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/299
It adds the `[JsonConverter(typeof(NextLinkConverter))]` attribute to the relevant `@odata.nextLink` properties so that urls may be decoded first to prevent issues with paging brought about by encoding done by the SDK. 
It also removes the DerivedTypeConverter attribute from `*CollectionResponse` objects as they do not have parents/children. This will enable them to use the native converters to improve performance of deserialization.
This PR should be merged in after https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/299
> NextLink initialization using the NextLinkConverter

- src/GraphODataTemplateWriter/CodeHelpers/Java/TypeHelperJava.cs
- test/Typewriter.Test/TestDataJava/com/microsoft/graph2/callrecords/requests/CallRecordItemRequestBuilder.java
- test/Typewriter.Test/TestDataJavaBeta/com/microsoft/graph2/callrecords/requests/CallRecordItemRequestBuilder.java
- fixes a bug where imports for navigation property of collection for composable methods would be incorrect in java
- updates java test data
related to
https://github.com/microsoftgraph/msgraph-sdk-java/pull/848
> fixes a bug for java with composable function and collection navigation properties

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
Fixes length check before serializing Enum collection
None
https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
> Fixes length check before serializing an Enum collection

- .azure-pipelines/generation-pipeline.yml
Replaces current PHP beta stage that writes models to the v1 repo with the test PHP beta stage config that writes to the new Beta SDK repo
https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
> Make PHP beta migration test stage the official beta stage in PHP v2

- .azure-pipelines/generation-pipeline.yml
Removes the test Beta PHP stage used to push Beta model updates to the new Beta SDK repo.
The Beta SDK repo will be updated via manual runs of `support/php-2.x.x` to allow breaking model template changes currently on `support/php-2.x.x` to not be overwritten by weekly generation runs.
The removed test migration changes will be made the official beta stage in `support/php-2.x.x` which will later be merged to dev when v2 is stable. PR for that https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/600
https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
> Remove beta updates to PHP beta SDK library until v2 is stable

- GraphODataTemplateWriter.Test/ContainmentTests.cs
- GraphODataTemplateWriter.Test/Edmx/Containment.xml
- Templates/templates/CSharp/Base/CollectionRequest.Base.template.tt
- Templates/templates/CSharp/Base/ICollectionRequest.Base.template.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/336
This PR fixes the blocked generation of POST(Add) request builders for some objects due to the expectation in the generator that posts $ref segments should have the following expectations
```cs
/// 1. If a navigation property specifies "ContainsTarget='true'", it is self-contained. 
///    Generate a direct path to the item (ie "parent/child").
/// 2. If a navigation property does not specify ContainsTarget but there is a defined EntitySet 
///    of the given type, it is a reference relationship. Generate a reference path to the item (ie "item/$ref").
/// 3. If a navigation property does not have a defined EntitySet but there is a Singleton which has 
///    a self-contained reference to the given type, we …
```
> Fix for missing AddAsync methods for collection references

- .github/CODEOWNERS
This PR adds @Ndiritu, @andrueastman, @SilasKenneth to the codeowners of the Generator codebase
> Adds code owners

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
When calling jsonSerialize() on PHP entities if the properties of that entity contain any other entities it does not serialize them properly. This pull request adds in the recursive serialization for entities.
> added recursive json serialization for entities

- .azure-pipelines/generation-pipeline.yml
This PR fixes the generation pipeline to ensure the capture metadata stages wait for the `stage_build_and_publish_kiota` stage to complete in order to ensure the step is not skipped (the conditions for the stage rely on the completion of the `stage_build_and_publish_kiota`  stage). 
This caused the generation pipeline to skip capture metadata stages and thus the later generation stages failed.
> Fix generation pipeline to depend on stage_build_and_publish_kiota stage

- .gitmodules
This PR switches the submodule reference from our fork under microsoftgraph to the upstream in OneDrive in an effort to avoid code duplication and confusion.
If you have this repo cloned locally, you'll need to update the submodule after pulling those changes:
```shell
git submodule deinit apidoctor
rm -r .\.git\modules\apidoctor\ -Force
git submodule init apidoctor
git submodule update --remote --merge
```
No impact on code generation.
Related
https://github.com/OneDrive/apidoctor/pull/102
https://github.com/microsoftgraph/apidoctor/pull/34
> - switches api doctor module reference to upstream

- .azure-pipelines/generation-templates/build-and-publish-typewriter.yml
- .github/workflows/dotnet.yml
This PR is part of the work from https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/672
It fixes some paths left out in the pipelines that are broken after the upgrade to net6.0 in the typewriter project.
> Fix pipeline paths after dotnet 6 update

- .azure-pipelines/generation-templates/build-and-publish-kiota.yml
- .azure-pipelines/generation-templates/build-and-publish-typewriter.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/dotnet.yml
All the dotnet cli tasks output these two messages during execution.
```
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
```
```
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and …
```
> updates dotnet cli tasks

- .azure-pipelines/generation-pipeline.yml
This PR renames the target kiota generated client to `BaseGraphServiceClient` for extensibility reasons
> Rename target client

- .azure-pipelines/generation-templates/dotnet-kiota.yml
This PR removes package authentication steps in the Kiota dotnet generation.
This is no longer needed as the packages are now public and causes the build to fail due to changed project structure to reflect this.
> [Dotnet] Remove package authentication

- .azure-pipelines/generation-pipeline.yml
This PR changes the target namespace to `Microsoft.Graph` after fix applied in https://github.com/microsoft/kiota/pull/1489 
Generation run can be viewed at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=71662&view=results
> Changes target namespace

- scripts/clean-typescript-files.ps1
Exclude manually edited files for TS in directory `src\graphclient` from deletion
Resolves https://github.com/microsoftgraph/msgraph-sdk-typescript/issues/33
> Exclude TS files in folder graphclient from deletion

- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
This PR closes #735 
Generation failure was caused by the existence of multiple types with the same name across multiple namespaces (`microsoft.graph.ediscovery.datasource` and `microsoft.graph.security.datasource`). 
Due to the current lookup only using the name, some request builders would fail to generate as the type found during the lookup was always the first type in the list and would thus not generate the request builders for the second item with a similar name.
This PR therefore updates the lookup to use the full name to ensure the type found is the expected type.
Generation run  :
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=73776&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9
> Use full name for lookup of reference types

- Templates/templates/CSharp/Model/ComplexType.cs.tt
- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/EmptyBaseComplexTypeRequest.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/EmptyComplexType.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/EmptyComplexTypeWithBaseType.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/model/UserAgent.cs
This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1328
It updates the Typewriter generator to behave consistently for both complex and abstract types by removing the abstract modifier on complex types.
This therefore unblocks instances where new derived types of abstract complex types are added to the metadata leading to the throwing of an exception. 
With this change, the derivedTypeConverter should be able to instantiate and return an instance of the base complex type in the event the user has not updated to a version where the derived type is not present in the metadata.
Generation PRs
V1 - https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1340
Beta - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/443
> [Dotnet] Remove abstract modifier for complex types

- .vscode/launch.json
Updates the Launch.json file to use net6.0 instead of net5.0.
> update launch Json file to use net6.0

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/language-generation-kiota.yml
This PR fixes the Kiota generation pipeline to allow extra arguments to passed to the Kiota executable.
This in turn enable the passing of the `-b` flag to enable the backing store in supported scenarios.
Generation run can viewed at the link below.
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=72629&view=results
> Enables the backing store on Kiota generation

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
According to [this PR](https://github.com/microsoftgraph/msgraph-sdk-php/pull/862) PHP model template requires update. Template generated function `jsonSerialize()` return type must be compatible with `JsonSerializable::jsonSerialize(): mixed` since PHP 8.1.
This PR should not contain any breaking changes as the return type was introduced in php7.0 and does not conflict with the actual return value of the function.
> Define explicit jsonSerialize() return type

- scripts/generate-open-api.ps1
This PR fixes the generation pipeline to align to the latest hidi options.
Before the log level was set as `--loglevel` but is now set as `--log-level`
> Update pipeline to align to latest Hidi  options

- scripts/copy-dotnet-models-kiota.ps1
- scripts/copy-java-models-kiota.ps1
- scripts/copy-php-kiota.ps1
This PR closes https://github.com/PowerShell/PowerShell/issues/13352
It fixes an issue where generated code in the first folder would be placed in the incorrect folder due to an issue with the  powershell `Move-Item` cmdlet.
https://github.com/PowerShell/PowerShell/issues/13352
This PR fixes the issue by making sure the destination folder exists.
> Fix for incorrect directory structure

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
Reverts a previous change where we explicitly defined the `jsonSerialize()`  return type to `array` to prevent [this warning on PHP 8.1](https://github.com/microsoftgraph/msgraph-sdk-php/issues/753). See [this](https://php.watch/versions/8.1/internal-method-return-types) for more context on the warning.
Explicitly defining the return type didn't seem like a breaking change since the method always returned an array. However we missed the case that a developer may have extended the model leading to https://github.com/microsoftgraph/msgraph-sdk-php/issues/919 being reported.
This PR uses the `#[\ReturnTypeWillChange]` attribute instead to prevent the PHP 8.1 warning from being emitted without breaking BC.
[v1 diff](https://github.com/microsoftgraph/msgraph-sdk-php/compare/v1.0/pipelinebuild/7 …
> PHP - Add ReturnTypeWillChange attribute to jsonSerialize()

- .azure-pipelines/generation-templates/capture-openapi.yml
- adds a step to validate OpenAPI docs right before checkin
N/A
N/A
- fixes #782
- blocked on https://github.com/microsoftgraph/msgraph-metadata/pull/173
> adds a step to validate OpenAPI docs right before checkin

- src/Typewriter/DocAnnotationWriter.cs
When generating/enriching CSDL with annotations from documentation, the whole doc set, i.e. v1.0 and beta, is used despite a specific version having been set. This has led to links and descriptions annotation values from one version being mixed up in another version's CSDL.
This PR ensures we only use documentation from the specified version to generate annotations.
`-v Info -m "\msgraph-metadata\v1.0_metadata.xml" -o \generated-metadata -g TransformWithDocs -t \msgraph-metadata\transforms\csdl\preprocess_csdl.xsl -d \microsoft-graph-docs -e v1.0 -r false -a true -f cleanMetadataWithDescriptionsAndAnnotationsAndErrors`
Fixes #790
> Typewriter: Load DocSet for specified version only

- Templates/templates/CSharp/Model/ComplexType.cs.tt
- Templates/templates/CSharp/Model/EntityType.cs.tt
- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
This PR fixes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/814 and is related to https://github.com/microsoft/Vipr/pull/255
It fixes generation issues discovered in the beta staging metadata after the introduction of the `Microsoft.Graph.IdentityGovernance`
Changes include
- Adds `Microsoft.Graph.IdentityGovernance` to the reserved namespace list as it collides with the `Microsoft.Graph.IdentityGovernance` type
- Ensure the type names in properties in the models are disambiguated to avoid using reserved model names
Generation run - https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=83976&view=logs&j=59c05382-99ff-5215-87ed-89074293151a
Raptor Run - https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_bui …
> Dotnet Beta generation fixes

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/java-kiota.yml
Change the namespace for the Kiota generated java files from Microsoft.Graph to Com.Microsoft.Graph. This fixes the issue of entities and classes not being able to find certain classes due to a truncated namespace.
> namespace java kiota

- src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs
This PR fixes the broken beta staging raptor pipeline due to the newly introduced `Microsoft.Graph.DeviceManagement` namespace which conflicts with the `DeviceManagement` type in the `Microsoft.Graph` namespace in dotnet.
Successful run after change can be found at the link below
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=85497&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=6278c56e-b9dd-5471-9c3c-f3062039459c
> Fix conflicting type and namespace due to new Microsoft.Graph.DeviceManagement namespace

- .azure-pipelines/generation-pipeline.yml
- scripts/clean-go-files.ps1
Renames default client generated by go from `GraphServiceClient` to `GraphBaseServiceClient`. This should allow adding manually edited files later.
Partially addresses https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/88
###
Blocked by 
https://github.com/microsoftgraph/msgraph-sdk-go/pull/277
https://github.com/microsoftgraph/msgraph-beta-sdk-go/pull/155
> Adds a base client for go generation

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/Metadata/MetadataWithSubNamespaces.xml
- test/Typewriter.Test/TestDataObjC/Models/MSGraphTestType.h
- test/Typewriter.Test/TestDataObjC/Models/MSGraphTestType.m
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/TestType.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/TestType.php
- test/Typewriter.Test/TestDataTypeScript/com/microsoft/graph/src/Microsoft-graph.d.ts
- test/Typewriter.Test/TestDataTypeScriptBeta/com/microsoft/graph/src/Microsoft-graph.d.ts
Ensure's primitive collection types are properly represented in documentation of model getters & setters.
https://github.com/microsoftgraph/msgraph-sdk-php/pull/1022
https://github.com/microsoftgraph/msgraph-sdk-php/pull/1023
https://github.com/microsoftgraph/msgraph-sdk-php/issues/1024
> PHP - Fix representation of collections of primitive types

- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
This PR fixes a null reference exception in the `GetComposableFunctionReturnTypeNavigations` due to a failed cast.
Related to changes made in https://github.com/microsoftgraph/msgraph-metadata/pull/213
> Fix null reference exception when method return type is an odata primitive.

- Templates/templates/Java/requests/BaseMethodRequest.java.tt
- Templates/templates/Java/requests/BaseMethodRequestBuilder.java.tt
https://github.com/microsoftgraph/msgraph-sdk-java/issues/1063
As noted in this issue, we are not adding function options to our request options on all methods which include parameters. The issue is due to the fact that we do not check the method overloads for whether they have parameters or not when we generate the BuildRequest() methods. In some cases the topmost Ocdm method of the class does not have parameters and in such cases, we fail to add these parameters to the request options. By checking all instances of the method, and whether any overloads include parameters, we can cover scenarios where some overloads have parameters and others don't.
> add funcOptions to requestOptions

- Templates/templates/PHP/Model/EntityType.php.tt
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/GraphPrint.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/Entity.php
- test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/GraphPrint.php
Stream properties in models were NOT previously being serialized into the request payload.
This fix casts the streams to "string" which rewinds the stream & reads the stream's contents into a string
https://github.com/microsoftgraph/msgraph-sdk-php/pull/1055/files
https://github.com/microsoftgraph/msgraph-sdk-php/pull/1056/files
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1052
> Serialize stream properties in PHP models

- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/capture-openapi.yml
- .azure-pipelines/generation-templates/use-dotnet-sdk.yml
This PR fixes some failing steps in generation pipeline due to some tools still using NET6.
In summary, changes include,
- Update `use-dotnet-sdk.yml` to take in the dotnet version as a param so that steps needing NET6 can choose the version. particularly Hidi.
> Fix generation pipeline due to missing dotnet version

- .azure-pipelines/generation-templates/capture-openapi.yml
This PR fixes the openAPI generation step that fails as Hidi is now an .NET 7 app
> Fix Hidi dotnet version

- test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
`Entity.php` is always written to console during test runs making it confusing to trace issues with failed builds
e.g. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/actions/runs/3907997316/jobs/6677759915
This PR disables writing Entity.php to the test context.
> Disable writing PHP model file to test context

- Templates/templates/CSharp/Base/IRequestBuilder.Base.template.tt
- Templates/templates/CSharp/Base/RequestBuilder.Base.template.tt
- Templates/templates/CSharp/Requests/EntityCollectionRequestBuilder.cs.tt
- Templates/templates/CSharp/Requests/EntityRequestBuilder.cs.tt
- Templates/templates/CSharp/Requests/IEntityCollectionRequestBuilder.cs.tt
- Templates/templates/CSharp/Requests/IEntityRequestBuilder.cs.tt
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/CloudCommunicationsCallRecordsCollectionRequestBuilder.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/ICloudCommunicationsCallRecordsCollectionRequestBuilder.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/ISegmentRequestBuilder.cs
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph2/callrecords/requests/SegmentRequestBuilder.cs
This PR fixes a bug where return types and parameters for request builders odata methods would not be aware of namespace context causing build issues on smoke tests.
> Fixes namespace resolution for odata function/actions

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/dotnet-kiota.yml
This PR fixes the generation pipeline to use the Hidi validation after changes made in https://github.com/microsoftgraph/msgraph-metadata/pull/257 make the pipeline point to non existing files.
Other changes include
- Updates pool to `1es-ubuntu-latest` to allow for more jobs to run in parallel.
- Updates the dotnet task to build the csproj directly.
Sample run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=105144&view=results
> Fix generation pipeline to use Hidi validation

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- Templates/templates/CSharp/Model/EnumType.cs.tt
- test/Typewriter.Test/Metadata/MetadataMultipleNamespaces.xml
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/model/RoleEligibilityRequestFilterByCurrentUserOptions.cs
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/models/RoleEligibilityRequestFilterByCurrentUserOptions.java
- test/Typewriter.Test/TestDataJavaBeta/com/microsoft/graph/models/RoleEligibilityRequestFilterByCurrentUserOptions.java
This PR  unblock generation of beta SDKs in the current week,
In summary changes include.
- Remove smoke tests from metadata stages to prevent single point of failure for other SDKs
- Fixes dotnet generation to ensure the System namespace is included when Enum properties are deprecated.
- Updated test metadata to capture this scenario.
Sample run at https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=105923&view=results
> Fixes beta SDKs generation

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/language-generation-kiota.yml
- .azure-pipelines/generation-templates/language-generation.yml
- scripts/create-pull-request.ps1
This updates the generation pipeline to be able to generate PRs by adding a optional step to generate PR if skipCI conditions are met and can be enabled per repository.
Due to some repositories having working mechanisms at the moment such as Go, Ruby, Java this behaviour is disabled by default and is opt-in.
Sample run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=106646&view=logs&j=11f01158-f524-5966-40fd-acf3ebd4803b&t=7b03cdbb-a21e-5d67-a9fd-922bc6e7df2b
Sample PR - https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1652
> Generates PRs from ADO

- .azure-pipelines/generation-pipeline.yml
This PR retires the typewriter generation for the dotnet sdk to work with Kiota.
> Retires typewriter generation

- Templates/templates/Java/requests/BaseEntityCollectionRequestBuilder.java.tt
This PR partially addresses the failure at https://github.com/microsoftgraph/msgraph-beta-sdk-java/actions/runs/4296032145/jobs/7487243083
It ensures the collection request builder picks up the unique methods and does not regenerate inherited methods if there's one already declared.
> Use distinct methods in collection request builders in java

- Templates/templates/Java/requests/BaseMethodRequestBuilder.java.tt
- src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
- src/GraphODataTemplateWriter/OdcmMethodEqualityComparer.cs
- test/Typewriter.Test/Metadata/MetadataMultipleNamespaces.xml
- test/Typewriter.Test/TestDataCSharp/com/microsoft/graph/requests/UserValidatePropertiesRequestBuilder.cs
- test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/UserCollectionRequestBuilder.java
- test/Typewriter.Test/TestDataJavaBeta/com/microsoft/graph/requests/UserCollectionRequestBuilder.java
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/532
Fixes the incorrect generation of multiple constructors when an action/function is both bound to a type and a collection of the type.
This is done by adding a method comparer that can ignore checking if the method is bound to a collection.
Test metadata has been updated to capture this and updated generation at https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/534
> Fixes multiple constrcutors in java

- .azure-pipelines/generation-templates/capture-openapi.yml
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1752#issuecomment-1477780228
The parallel stages for caputuring the openAPI files publish all the 4 yaml files but only update one of the files. This causes subsequent stages to potentially use unmodified/stale version as the publish stage end up publishing the same file used before. 
This PR updates the publishing of artifacts to only publish the file generated at the specified step to avoid the situation above. 
Sample generation run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=110760&view=results
> Only publish the updated yaml file.

- scripts/generate-open-api.ps1
The main OpenAPI document should generate from the document  with the Errors annotations while others do not need these files.
Fixes #980
> Fix: conditionally generate OpenAPI documents

- .azure-pipelines/generation-templates/capture-openapi.yml
since we've added multiple open api convert settings and profiles, the conversion job often gets caught in a racing condition. This change commits all the files for a given version to reduce the likeliness of that happening. Ideally we'd do it for both versions at once but we'd lose the ability to generate for a single version at a time if we did that unless we seriously revamp the pipeline definition to use a matrix for versions for that aspect
> - fixes a racing condition when publishing openapi descriptions

- .azure-pipelines/generation-pipeline.yml
Skips generation of me endpoint to reduce SDK size
Part of https://github.com/microsoftgraph/msgraph-sdk-python/issues/150
> Exclude me endpoint from generation

- .github/policies/MSGraph-SDK-Code-Generator-branch-protection.yml
Capture current policy state so that we can make versioned changes to branch protection policies. This will enable policy history, auditing, review, standardization, and templatization. We will update policy in later PR.
We can ignore the rules that state: `At least one value under RequiredStatusChecks must be specified when RequiresStrictStatusChecks is true.` or `RequiresStrictStatusChecks must be true when specifying RequiredStatusChecks.` This is getting removed.
* https://github.com/microsoft/GitOps.Branches/pull/73
* https://github.com/microsoft/GitOps.Branches/issues/72
This branch protection policy will not take effect until https://github.com/microsoftgraph/.github/blob/main/policies/branch-protection-sdks.yml has been removed.
> chore: capture initial branch policy settings

- .azure-pipelines/generation-pipeline.yml
Enables the backing store by default for Python v1 and Beta.
> Enable backing store during python generation

- .azure-pipelines/generation-pipeline.yml
In preparation for the release candidate of the next version of the Java SDK we must enable the backing store.
> Enable backing store for next version of Java generation

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- scripts/download-diff-metadata.ps1
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/203
Switches the source of beta metadata from the live site (https://graph.microsoft.com/beta/$metadata) to the CSDL files in the _./schema_ folder in the metadata repo. This file gets maintained by the Identity folks and it is an annotation-enriched version of the live site file.
We are validating and testing this move with the `beta` metadata first then switch over v1.0 later.
> Updates beta metadata source

- .azure-pipelines/generation-pipeline.yml
Fixes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/1139
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/556
Related to: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1113
> Switches `v1.0` metadata source from livesite to local CSDL file in metadata repo.

- scripts/generate-open-api.ps1
Changes in https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1142 added the `-NoNewline` parameter to the `Set-Content` command.
However, as `Get-Content` is called without `-Raw` parameter, the content is split to multiple strings therefore results to all the newlines in the file removed causing parsing errors. 
This PR ensures the file content is read appropriately to prevent an unparsable yaml
> Fix missing new lines in openapi doc

- .azure-pipelines/generation-pipeline.yml
The connection `microsoftgraph` is no longer authorized after changes made recently.
> Update connection to fetch sources.

- .azure-pipelines/generation-templates/java-kiota.yml
Part of the Java pipeline included the incrementMinorVersion script, this was never added to the Kiota versions since preview never required a version bump. This should be reintroduced now that iv6 is GA.
> Add incrementMinorVersion script to java again

- .azure-pipelines/generation-templates/build-and-publish-kiota.yml
- .azure-pipelines/generation-templates/capture-metadata.yml
- .azure-pipelines/generation-templates/capture-openapi.yml
- .azure-pipelines/generation-templates/set-up-for-generation-kiota.yml
Hidi is a net 7.0 app causing failure in metadata generation
Sample run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=138236&view=logs&j=0c914960-8b50-5299-c9aa-dd3c9595168e
Will rerun SDK generation pipeline after merge.
> Fixes generation pipeline

- .azure-pipelines/generation-templates/java-kiota.yml
Related to https://github.com/microsoftgraph/msgraph-sdk-java/pull/1939
Removes the increment version step for java as the script is removed in the above change. This unlbocks java sdk generation on the weekly pipeline.
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=144721&view=logs&jobId=c52f3745-d4e6-5486-f10a-a43ce9aa535b&j=c52f3745-d4e6-5486-f10a-a43ce9aa535b&t=71b229cf-4300-5726-07d9-c4fd33aeb191
> [Java] Fix increment version

- .azure-pipelines/generation-pipeline.yml
`dev` branches no longer exists so pipelines cannot perform checkouts.
> Fix pipeline checkout branches for java

- .azure-pipelines/generation-pipeline.yml
- .azure-pipelines/generation-templates/go.yml
Removes the manual version bump script for go and rely on `release please` configured in the repo
Follow up to PR's https://github.com/microsoftgraph/msgraph-sdk-go/pull/713 and https://github.com/microsoftgraph/msgraph-beta-sdk-go/pull/418
> feat: remove manual version bump, rely on release please for go

- .azure-pipelines/generation-templates/java-kiota.yml
- .azure-pipelines/generation-templates/typescript-sdk.yml
Fixes failing copy of dom export file in TS pipeline
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=162820&view=logs&j=b56651c9-d0cc-5029-fad3-f9889cfa9c40&t=f95306b9-2fa1-54d2-3f1c-886a1f224e7f
> fix: overwrite existing file if present.

- .azure-pipelines/generation-templates/language-generation-kiota.yml
- scripts/copy-typescript-sdk-models.ps1
Fixes #1293 
Also fixes TS generation failure due to non existent paths.
> feat: exclude TCP APIs from language generation.

- .azure-pipelines/generation-templates/capture-openapi.yml
hidi v2 is now published on a -preview version.
defective hidi v1 versions have been deprecated
a new version of hidi v1 has been published, to benefit from recent changes in yoko but also for sanity
related #1295
> chore: unpins hidi

- .azure-pipelines/generation-templates/build-and-publish-kiota.yml
- .azure-pipelines/generation-templates/set-up-for-generation-kiota.yml
Related to changes in https://github.com/microsoft/kiota/pull/6006
Kiota needs a NET 9 target for it to be built/run.
> chore: Fix SDK generation

- .azure-pipelines/generation-templates/dotnet-kiota.yml
> ci: removes dotnet build as it's redudant with the PR CI and often pushes us over the 1 hour time limit for the generation

- .azure-pipelines/generation-pipeline.yml
> ci: remove old reference to objc repo which was archived almost 2 years ago now

- .azure-pipelines/generation-templates/capture-metadata.yml
> fix: metadata validation is missing hidi installation

- .azure-pipelines/generation-templates/capture-openapi.yml
> ci: fixes another instance of the wrong version of dotnet being used for hidi

- scripts/create-pull-request.ps1
This is PR will be coupled with a few other ones to handle beta typing releases. Specifically, this has a preview patch version, but we've bumping minor version so we want to maintain consistency.
> ci: update script to special case for beta typing versioning
