microsoftgraph/MSGraph-SDK-Code-Generator

Templates/Android/BaseModel.template.tt
Templates/Android/extensions/MethodCollectionPage.java.tt
Templates/Android/generated/BaseMethodBodyRequest.java.tt
Templates/Android/generated/BaseMethodCollectionPage.java.tt
Templates/Android/generated/BaseMethodCollectionRequest.java.tt
Templates/Android/generated/IBaseMethodBodyRequest.java.tt
src/GraphODataTemplateWriter/.config/AndroidSettings.json
src/GraphODataTemplateWriter/TemplateProcessor/TemplateProcessor.cs

- Prevented incorrect generation of singular requests for collections
methods
- Prevented incorrect generation of collections requests for singular
methods
- Added logging to indicate which sub processor is running

Updates to Android Generation

---

Templates/ObjC/Base/SharedObjC.template.tt
Templates/ObjC/Models/Models.h.tt
src/GraphODataTemplateWriter/CodeHelpers/ObjC/TypeHelperObjC.cs

MSDate class wrapping NSDate and exposing year/month/day properties has been added separately to the core SDK.

Add Edm.Date support

---

src/GraphODataTemplateWriter/CodeHelpers/Android/TypeHelperAndroid.cs

Template modifications for `Edm.Date` to use `com.microsoft.graph.model.DateOnly`

Updating TypeHelper to use custom DateOnly type

---

Templates/ObjC/Requests/EntityCollectionRequest.m.tt
Templates/ObjC/Requests/EntityRequest.m.tt

The Tasks API has a property task. This causes a variable name conflict with the URLSessionDataTask task.

There is a Task API in beta which causes a naming conflict with the local variable

---

graphmeta_excel_noannots.xml

Here's the meta we'll dev against for Excel

Annotationless $metadata for Excel v1

---

Templates/Android/generated/BaseEntityCollectionReferenceRequest.java.tt

Replace static newDirectoryObject reference to dynamic method parameter reference.

Replace static newDirectoryObject reference to dynamic method parameter reference.

---

Templates/PHP/Model/ComplexType.php.tt
Templates/PHP/Model/EntityType.php.tt

Fixes found through functional tests of the PHP SDK

Update PHP templates

---

Templates/Android/generated/BaseEntityCollectionReferenceRequest.java.tt
Templates/Android/generated/BaseEntityCollectionRequest.java.tt
Templates/PHP/Model/EntityType.php.tt

We have to do this manually because Enum is a custom class not handled by PHP Core

Bugfix for serializing enums in PHP

---

Templates/Android/extensions/Client.java.tt

See microsoftgraph/msgraph-sdk-android#42

Make Android logger public

---

Templates/Android/extensions/Enum.java.tt

See  https://github.com/microsoftgraph/msgraph-sdk-android/pull/68

Sanitize enums by uppercase

---

Templates/PHP/Model/EnumType.php.tt

Set reserved word enum values to strings instead of ints

---

Templates/CSharp/Model/MethodRequestBody.cs.tt
Templates/CSharp/Requests/MethodRequest.cs.tt
Templates/CSharp/Requests/MethodRequestBuilder.cs.tt

Verified through diff that these changes do not affect the existing client library. This should fix the generation issues.

Dev update method request

---

Templates/CSharp/Model/MethodRequestBody.cs.tt
Templates/CSharp/Requests/MethodRequest.cs.tt
Templates/CSharp/Requests/MethodRequestBuilder.cs.tt

Update master with template changes

---

metadata/v1.0_2017_12_14.xml
metadata/v1.0_2017_12_14_descriptions.xml

This metadata should be the target metadata for the Jan/Feb 2018 release of the graph client libraries.

Added the December 2017 metadata.

---

GraphODataTemplateWriter.Test/GraphODataTemplateWriter.Test.csproj
GraphODataTemplateWriter.Test/Properties/AssemblyInfo.cs
GraphODataTemplateWriter.Test/packages.config
GraphODataTemplateWriter.sln

Creates a new unit test project with references to the Code Writer and VIPR. This had a side-effect of bumping the build version up to msbuild15.

Unit test infrastructure

---

Templates/Android/generated/BaseEntity.java.tt
Templates/Java/models_generated/BaseEntity.java.tt

Fixes https://github.com/microsoftgraph/msgraph-sdk-android/issues/72

Odata type

---

GraphODataTemplateWriter.Test/ContainmentTests.cs
GraphODataTemplateWriter.Test/Edmx/Containment.xml
GraphODataTemplateWriter.Test/GraphODataTemplateWriter.Test.csproj
Templates/Android/generated/BaseEntityCollectionReferenceRequest.java.tt
Templates/CSharp/Base/CollectionRequest.Base.template.tt
src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs

Handles the case where a navigation property references an implicit EntitySet of a singleton.

Implicit containment

---

Templates/Java/requests_generated/BaseEntityRequest.java.tt
Templates/Java/requests_generated/IBaseEntityRequest.java.tt

Accepting correct method parameter during API call resolves ClassCastException.

Fix ClassCastException during delete API call

---

Templates/Java/models_generated/BaseMethodBody.java.tt
Templates/Java/requests_generated/BaseEntityRequestBuilder.java.tt
Templates/Java/requests_generated/IBaseEntityRequestBuilder.java.tt

- these are new additions and required handling for EnumSet
Issues fixed:
- https://github.com/microsoftgraph/msgraph-sdk-java/issues/77
- https://github.com/microsoftgraph/msgraph-sdk-java/issues/44
PR in java SDK with corresponding generated java files: https://github.com/microsoftgraph/msgraph-sdk-java/pull/125

Fixing java template for import statement

---

src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeHelperTypeScript.cs

Add support for handling EDM.Decimal for typings
https://github.com/microsoftgraph/msgraph-typescript-typings/issues/44

Convert edm.Decimal to Typescript number

---

src/Typewriter/MetadataPreprocessor.cs

This unblocks beta generation for .net.

Added preprocess rule for new intune navigation

---

src/Typewriter/MetadataPreprocessor.cs

Add contains target for new entities.

---

Templates/TypeScript/src/entity_types.ts.tt
Templates/TypeScript/src/utils.tt

Fixed linting error in the typescript types generation:
* [max-line-length](https://palantir.github.io/tslint/rules/max-line-length)
* [no-empty-interface](https://palantir.github.io/tslint/rules/no-empty-interface)
* [interface-name](https://palantir.github.io/tslint/rules/interface-name)

Fix linter issues for definitely typed

---

src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs

@ramsessanchez you are required for sign-off.

Fix import and test

---

Templates/PHP/Model/ComplexType.php.tt
src/GraphODataTemplateWriter/CodeHelpers/PHP/CodeWriterPHP.cs

* This will update all complex type files
* e6a1c3f updates the headers in generated files. All files will be changed.

Fix base class for PHP complex type

---

Templates/PHP/Model/ComplexType.php.tt

References https://github.com/microsoftgraph/msgraph-sdk-php/pull/295

Set complex type base as entity for now.

---

Templates/TypeScript/src/entity_types.ts.tt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46439

Add export for nullableoption<t>

---

Templates/TypeScript/src/entity_types.ts.tt
src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeScriptNamespace.cs
test/Typewriter.Test/MultipleNamespacesTestRunner.cs

Styling the code. Addressing the [comment](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/288#discussion_r486669006)

Typescripts namespace styling change

---

.github/dependabot.yml

We're behind on a number of libraries, this should help up stay current

- adds dependabot configuration for repo

---

.editorconfig

- adds editor config for template files

- adds editor config to avoid tab and space disruptencies

---

.github/dependabot.yml

- adds submodules as something to update automatically since vipr is a submodule

- adds submodule as an ecosystem to update

---

.editorconfig
Typewriter.sln

related #336
https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/115

- updates solution to include editor config and adds standard rules for CSharp

---

Templates/Java/requests_extensions/BaseEntityCollectionRequestBuilder.java.tt

addresses PR comments from https://github.com/microsoftgraph/msgraph-sdk-java/pull/584
related #339
Note: the test files update has been run but didn't generate any difference

- adds condition to avoid adding reference when unecessary

---

mono_build.sh

We are thankful for mono, we no longer need the special script.

Remove mono script

---

.github/workflows/dotnet.yml
test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs

- adds a pipeline for PR validation
> Note: I disabled the following [ADO pipeline](https://o365exchange.visualstudio.com/O365%20Sandbox/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1728) as it replaces it

- adds a pipeline for unit test validation

---

.vscode/launch.json
.vscode/tasks.json
Templates/Java/models_extensions/BaseMethodParameterSet.java.tt
src/GraphODataTemplateWriter/CodeHelpers/Java/TypeHelperJava.cs
src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs

This is a follow up on #368 which fixes an issue where parameters for overloads methods would not be generated.
It also adds debug files for vs code :)

java optional parameters bugfixes

---

Templates/templates/Java/requests/BaseClient.java.tt

related to latest commits in https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42

- aligns java service client with authentication changes in core lib

---

.azure-pipelines/generation-pipeline.yml

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml

Fix cron syntax

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/language-generation.yml
scripts/git-push-files.ps1

Add a parameter to override skip ci flag

---

scripts/git-push-cleanmetadata.ps1

Add git pull before git push

---

src/Typewriter/DocAnnotationWriter.cs
src/Typewriter/Generator.cs

Fix synchronous method signatures and calling patterns

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/language-generation.yml
.azure-pipelines/generation-templates/typescript.yml

Changed references pointing to microsoftgraph/msgraph-typescript-typings#beta branch to the microsoftgraph/msgraph-beta-typescript-typings#main
Worked on these changes with @zengin. Thank you for the help!

Update generation pipeline to new typings beta repo

---

Templates/templates/Java/models/BaseEntity.java.tt

related https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/159
generation diff https://github.com/microsoftgraph/msgraph-sdk-java/pull/681

- renames reference to IUploadSession to match large file upload rename

---

Templates/templates/Java/requests/BaseEntityStreamRequestBuilder.java.tt
src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs

fixes #317
resulting changes https://github.com/microsoftgraph/msgraph-sdk-java/pull/679

- adds support for inherited odata methods in java v3

---

Typewriter.sln

Fixes #478
Steps followed:
1. Removed all references to Templates project
2. Removed Templates project from the solution.
3. Added back Templates project to the solution.
4. Added back project references.

Re-add Templates project to the Typewriter solution

---

src/GraphODataTemplateWriter/CodeHelpers/Java/TypeHelperJava.cs

- fixes missing nullability annotations

- fixes a bug where parameter sets would be missing non null annotations

---

.gitignore
src/Typewriter/Properties/launchSettings.json

Remove launchSettings.json for allowing customization

---

Templates/templates/Java/requests/BaseEntityRequestBuilder.java.tt

fixes #516
code-gen results https://github.com/microsoftgraph/msgraph-sdk-java/pull/728

- fixes an issue where ODSP paths would not be encorded properly

---

README.md
src/Typewriter/Generator.cs
src/Typewriter/Options.cs

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/545

Fix per review #545

---

Templates/templates/PHP/Model/ComplexType.php.tt
Templates/templates/PHP/Model/EntityType.php.tt
test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/Model/OnenotePage.php
test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/Model/OnenotePage.php

- Return `GuzzleHttp\Psr7\Utils::streamFor()` in favour of `GuzzleHttp\Psr7\stream_for()`

Release to main

---

scripts/download-diff-metadata.ps1

git pull before git push for metadata

---

.azure-pipelines/generation-pipeline.yml

Created a new branch (`support/php-2.x.x`) to be used to manually trigger breaking v1 service library changes to the v2 SDK preview.
(This PR merges into this new branch.)
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/599

Change default checkout branch to feat/2.0.0

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/build-and-publish-kiota.yml
.azure-pipelines/generation-templates/capture-openapi.yml
.azure-pipelines/generation-templates/download-kiota.yml
.azure-pipelines/generation-templates/go.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
.azure-pipelines/generation-templates/language-generation.yml
.azure-pipelines/generation-templates/set-up-for-generation.yml
scripts/clean-go-files.ps1
scripts/copy-go-models.ps1
scripts/git-push-cleanmetadata.ps1

- adds steps to build kiota
- adds pipeline steps for go generation
- adds steps to update the open api descriptions
Fixes https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/4
> Note : the microsoft orgs to get kiota's repo is currently setup on a service connection that belongs to me and using my PAT, we might want to change that but I don't think any of us has permissions to setup OAuth on the microsoft org
If you want to test the pipeline, make sure you select the feature/go-auth branch for kiota.
Do not merge before https://github.com/microsoft/kiota/pull/716

adds weekly generation for go using kiota

---

Templates/templates/TypeScript/src/entity_types.ts.tt
src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeScriptNamespace.cs
test/Typewriter.Test/Metadata/MetadataWithSubNamespaces.xml
test/Typewriter.Test/TestDataObjC/Models/MSGraphCallRecordsDisplayTemplate.h
test/Typewriter.Test/TestDataObjC/Models/MSGraphCallRecordsDisplayTemplate.m
test/Typewriter.Test/TestDataObjC/Models/MSGraphClientModels.h
test/Typewriter.Test/TestDataPHP/com/Microsoft/Graph/CallRecords/Model/DisplayTemplate.php
test/Typewriter.Test/TestDataPHPBeta/com/Beta/Microsoft/Graph/CallRecords/Model/DisplayTemplate.php
test/Typewriter.Test/TestDataTypeScript/com/microsoft/graph/src/Microsoft-graph.d.ts
test/Typewriter.Test/TestDataTypeScriptBeta/com/microsoft/graph/src/Microsoft-graph.d.ts

This PR merges the dev branch to main branch
The main changes include
- Hotfix for generation via #634 
- Recursive json serailization for PHP via #626 
Dependabot updates via 
- #625 
- #627
- #628 
- #629 
- #630 
- #631 
- #632

Merge dev to main

---

.azure-pipelines/generation-templates/build-and-publish-kiota.yml
.azure-pipelines/generation-templates/use-dotnet-sdk.yml

- adds dotnet 6 install for kiota

---

.azure-pipelines/generation-templates/use-dotnet-sdk.yml
.github/workflows/dotnet.yml
GraphODataTemplateWriter.Test/GraphODataTemplateWriter.Test.csproj
src/Typewriter/Typewriter.csproj
test/Typewriter.Test/Typewriter.Test.csproj

depends on https://github.com/microsoft/Vipr/pull/221
apidoctor can stay on net5 but aligning with would be better https://github.com/OneDrive/apidoctor/pull/112

upgrades to net6

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/dotnet-kiota.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
scripts/checkout-custom-base-branch.ps1
scripts/copy-dotnet-models-kiota.ps1

This PR enriches the generation pipelines to generate Kiota based SDK for dotnet on the feature/5.0 branch
Changes include
- Adding steps for beta/v1
- Adds ability to configure a custom base branch(feature/5.0)
Notes:
- Sample run can be found here for V1 generation - https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=67975&view=logs&j=0c914960-8b50-5299-c9aa-dd3c9595168e

[Dotnet] Kiota generation pipeline

---

.azure-pipelines/generation-templates/capture-openapi.yml

depends on https://github.com/microsoftgraph/msgraph-metadata/pull/117

- switches to Hidi for CSDL to OpenAPI conversion

---

.azure-pipelines/generation-templates/capture-metadata.yml
.azure-pipelines/generation-templates/capture-openapi.yml
scripts/run-typewriter-clean-metadata.ps1
src/Typewriter/Generator.cs
src/Typewriter/Options.cs
test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs

related https://github.com/microsoftgraph/msgraph-metadata/pull/110

adds a switch to include the error information or not

---

.azure-pipelines/generation-templates/capture-openapi.yml
scripts/generate-open-api.ps1

moves generate open api script and other fixes

---

.azure-pipelines/generation-pipeline.yml

Resolves comment from https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/718

Add beta to namespace

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/java-kiota.yml
scripts/clean-java-files-kiota.ps1
scripts/copy-java-models-kiota.ps1

Addressing https://github.com/microsoft/kiota/issues/372
https://github.com/microsoftgraph/msgraph-sdk-java/tree/kiota/v1.0/pipelinebuild/73535
https://github.com/microsoftgraph/msgraph-beta-sdk-java/tree/kiota/beta/pipelinebuild/73535

Kiota java generation

---

.azure-pipelines/generation-pipeline.yml

We aren't maintaining ObjC library and not enough customers are complaining.

Disable ObjC generation

---

.azure-pipelines/generation-templates/java-kiota.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
.azure-pipelines/generation-templates/set-up-for-generation-kiota.yml
scripts/clean-java-files-kiota.ps1
scripts/copy-java-models-kiota.ps1

Merge latest commits from dev to main. This should fix kiota-java library gen as well as other fixes.

Dev to Main

---

scripts/copy-java-models-kiota.ps1

This PR closes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/785
It fixes an issue of creating a new folder in Kiota Java generation as the folder already exists

Add force option for java generation

---

src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeHelperTypeScript.cs

fixes for https://github.com/microsoftgraph/msgraph-typescript-typings/pull/322
and https://github.com/microsoftgraph/msgraph-typescript-typings/issues/310

Set binary type to string

---

Templates/templates/Java/requests/BaseClient.java.tt
test/Typewriter.Test/TestDataJava/com/microsoft/graph/requests/GraphServiceClient.java
test/Typewriter.Test/TestDataJavaBeta/com/microsoft/graph/requests/GraphServiceClient.java

Dev to main so that the java fully qualified name implementation for properties becomes active.

Implement Java FIx

---

.azure-pipelines/generation-templates/java-kiota.yml

Prevent the Kiota Generator from removing the hand coded GraphServiceClient and the Constants class in the Info Folder.

Only delete files in src/main/java/com/Microsoft/graph/

---

src/GraphODataTemplateWriter/CodeHelpers/PHP/TypeHelperPHP.cs

Addresses https://github.com/microsoftgraph/msgraph-sdk-php/issues/791

Fixes conflicting `Microsoft.Graph.IdentityGovernance` namespace causing PHP Beta issue

---

.azure-pipelines/generation-pipeline.yml

Change base branch for Kiota Beta SDK

Change base branch for Kiota Beta SDK

---

.azure-pipelines/generation-templates/language-generation-kiota.yml

depends on https://github.com/microsoft/kiota/pull/1864

- updates kiota generation command

---

.azure-pipelines/generation-templates/build-and-publish-kiota.yml
.azure-pipelines/generation-templates/build-and-publish-typewriter.yml
.azure-pipelines/generation-templates/use-dotnet-sdk.yml
.github/workflows/dotnet.yml
.vscode/launch.json
GraphODataTemplateWriter.Test/GraphODataTemplateWriter.Test.csproj
src/Typewriter/Typewriter.csproj
test/Typewriter.Test/Typewriter.Test.csproj

- upgrades to dotnet 7

---

.azure-pipelines/generation-pipeline.yml

part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/979

Enable backing store - PHP

---

.azure-pipelines/generation-pipeline.yml

TS Typings - Changing from master to main

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/ruby.yml
scripts/clean-ruby-files.ps1
scripts/copy-ruby-models.ps1

fixes https://github.com/microsoft/kiota/issues/392

adds ruby weekly generation

---

scripts/clean-ruby-files.ps1

- removes exclusions as they are outside of the repo now

---

scripts/clean-ruby-files.ps1

- fixes a bug in the ruby files cleanup script

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/ruby.yml
scripts/clean-ruby-files.ps1

- updates ruby generation following shortening of  long paths

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/ruby.yml
scripts/update-ruby-barrel.ps1

- fixes a bug where root barrel would be overwritten

---

.azure-pipelines/generation-templates/capture-openapi.yml

related https://github.com/microsoftgraph/msgraph-metadata/pull/256

- fixes validation script for openapi documents

---

.azure-pipelines/generation-pipeline.yml
scripts/update-ruby-barrel.ps1

related https://github.com/microsoft/kiota/issues/2169

- aligns client in ruby with other languages

---

scripts/clean-ruby-files.ps1

- aligns ruby client name with other languages

---

scripts/update-ruby-barrel.ps1

- fixes a bug where barrels insert would fail on empty file in ruby

---

.azure-pipelines/generation-pipeline.yml

Add backing store flag for Go SDK generation

Generate go backing store

---

.azure-pipelines/generation-pipeline.yml

Exclude generation of 'me' path for Go sdk generation

Exclude me path in go generation

---

.azure-pipelines/generation-templates/capture-openapi.yml

Makes sure that the needed folders have been checked out before running the scripts

Fix: capture openapi checkout step

---

.azure-pipelines/generation-templates/capture-openapi.yml

Merges dev to main

---

.azure-pipelines/generation-pipeline.yml

Fixes beta artifact publishing

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
.azure-pipelines/generation-templates/language-generation.yml

Enables PR generation for all repos/languages by default to an opt-out scheme

Enable PR generation for all languages

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/cli-kiota.yml
scripts/copy-cli-models-kiota.ps1

Add CLI v1 generation to pipeline.
microsoftgraph/msgraph-cli#283
microsoftgraph/msgraph-sdk-go#453

Add CLI generation stage

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/capture-openapi.yml
.azure-pipelines/generation-templates/cli-kiota.yml
scripts/copy-cli-models-kiota.ps1
scripts/generate-open-api.ps1
src/Typewriter/Typewriter.csproj

- updates main branch for open api version information

---

.azure-pipelines/generation-pipeline.yml

Give a description of what your pull request does and what platform[s] it targets. Use the *breaking changes* tag if applicable. Breaking changes can include changes to generated code files which will impact API signature or behaviors, and changes to directory structures which may impact DevOp pipelines and scripts.

Exclude the /me endpoint from PHP Generation.

---

.azure-pipelines/generation-templates/cli-kiota.yml

Add the VSTS nuget feed to the CLI pipeline
None

Add vsts nuget feed

---

.azure-pipelines/generation-templates/cli-kiota.yml

Fixes undeclared parameters issue in the CLI generation pipeline.

Fix missing restore parameters

---

.azure-pipelines/generation-pipeline.yml

https://github.com/microsoftgraph/msgraph-sdk-java/issues/1437
Excludes the generation of the /me endpoint for Java_Kiota generation in v1.0 as well as in beta. 
Example generation can be seen here: https://github.com/microsoftgraph/msgraph-sdk-java/pull/1509

Disable /me endpoint for Kiota generated Java service library 

---

.azure-pipelines/generation-pipeline.yml

Update cli language name

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/cli-kiota.yml

Add automated generation for [microsoftgraph/msgraph-beta-cli](https://github.com/microsoftgraph/msgraph-beta-cli)
microsoftgraph/msgraph-cli#283

Add beta generation for CLI.

---

.github/policies/MSGraph-SDK-Code-Generator-branch-protection.yml
.github/workflows/codeql.yml

chore: update branch protection rules, codeql

---

.azure-pipelines/generation-templates/cli-kiota.yml
scripts/copy-cli-models-kiota.ps1

Update CLI users help content and show availability of 'me' command.
microsoftgraph/msgraph-cli#384

Add help content post-processing

---

.azure-pipelines/generation-templates/build-and-publish-kiota.yml
.azure-pipelines/generation-templates/set-up-for-generation-kiota.yml

Follow up to https://github.com/microsoft/kiota/pull/3734
Updates generation pipeline to generated using NET8 target for Kiota

Kiota generation using NET target

---

.azure-pipelines/generation-pipeline.yml

Update repoName in beta cli generation

---

.azure-pipelines/generation-pipeline.yml

Deprecate PHP SDK 1.x generation

---

.azure-pipelines/generation-pipeline.yml

- excludes me for typescript

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/capture-metadata.yml
scripts/download-diff-metadata.ps1
src/GraphODataTemplateWriter/GraphODataTemplateWriter.csproj
test/Typewriter.Test/Given_a_valid_metadata_file_to_Typewriter.cs
test/Typewriter.Test/Given_a_valid_metadata_file_to_metadata_preprocessor.cs
test/Typewriter.Test/MultipleNamespacesTestRunner.cs
test/Typewriter.Test/Typewriter.Test.csproj

Merges dev into main to deploy the change: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1113

Merges `dev` into `main`

---

.azure-pipelines/generation-pipeline.yml

- excludes me from ruby generation

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/typescript-sdk.yml
scripts/clean-typescript-files.ps1
scripts/copy-typescript-sdk-models.ps1
scripts/create-typescript-root-package.ps1
scripts/fix-typescript-fluent-packages-imports.ps1
scripts/generate-typescript.ps1

- fixes description, keywords and author for typescript packages

---

scripts/create-typescript-root-package.ps1

- adds ts index file update to creation script

---

.azure-pipelines/generation-pipeline.yml
scripts/clean-typescript-files.ps1
scripts/remove-typescript-fluent-api-from-main-package.ps1

- adds typescript beta generation

---

scripts/remove-typescript-fluent-api-from-main-package.ps1

- fixes a bug where the typescript request adapter would be removed

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
scripts/git-push-files.ps1

Add conventional commit message format to the code generated for the CLI

allow adding a commit message prefix for kiota languages

---

.azure-pipelines/generation-templates/capture-metadata.yml
.azure-pipelines/generation-templates/capture-openapi.yml

- switches hidi steps to net8 since it's supported now

---

.azure-pipelines/generation-templates/dotnet-kiota.yml

Runs version update script on generation for C# generation.
Sample run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=142491&view=results

Runs version update script on generation

---

.azure-pipelines/generation-templates/python.yml

- adds a script to automatically increment minor version for python

---

.azure-pipelines/generation-pipeline.yml

Add conventional commit message format to the code generated for the Java SDK

add conventional comit message for java SDK

---

.azure-pipelines/generation-templates/php-kiota.yml

- adds auto-increment of the PHP version

---

.azure-pipelines/generation-pipeline.yml

Removes the base branch for PR creation for PHP since we will be using the default `main` branch.
- https://github.com/microsoftgraph/msgraph-sdk-php/issues/1508
- https://github.com/microsoftgraph/msgraph-beta-sdk-php/issues/273

Remove dev as base branch for PHP generation PR creation.

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/java-kiota.yml

part of https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/940

Java Beta - Release please config preparation

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/java-kiota.yml

Merge `dev` to `main`

---

.azure-pipelines/generation-pipeline.yml

Related to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1234

Sync dev with main

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/php-kiota.yml

- Removes the step to bump version during PHP SDK generation.
- Change commit message to align with release-please commit message format.

Remove script to bump version + Change commit messages for generation PRs(PHP)

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/go.yml
.azure-pipelines/generation-templates/php-kiota.yml

Give a description of what your pull request does and what platform[s] it targets. Use the *breaking changes* tag if applicable. Breaking changes can include changes to generated code files which will impact API signature or behaviors, and changes to directory structures which may impact DevOp pipelines and scripts.

Latest Dev Changes

---

.azure-pipelines/generation-pipeline.yml

related https://github.com/microsoftgraph/msgraph-sdk-typescript/pull/604

chore: update typescript sdk base branch name

---

.azure-pipelines/generation-templates/python.yml

Scripts were removed by release please work at 
- https://github.com/microsoftgraph/msgraph-sdk-python/pull/757/files
- https://github.com/microsoftgraph/msgraph-beta-sdk-python/pull/439/files
Unblocks failures at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=154944&view=logs&j=7095b1dc-e98a-50ce-d678-79b151d35f06&t=538fc8ea-e663-5579-9d59-abbc0f3d694b

Removes incrementMinorVersion step for python generation

---

.azure-pipelines/generation-templates/dotnet-kiota.yml

Give a description of what your pull request does and what platform[s] it targets. Use the *breaking changes* tag if applicable. Breaking changes can include changes to generated code files which will impact API signature or behaviors, and changes to directory structures which may impact DevOp pipelines and scripts.

Remove the version bump step from dotnet pipeline.

---

.azure-pipelines/generation-pipeline.yml

Give a description of what your pull request does and what platform[s] it targets. Use the *breaking changes* tag if applicable. Breaking changes can include changes to generated code files which will impact API signature or behaviors, and changes to directory structures which may impact DevOp pipelines and scripts.

Change the default commit message and base branch for dotnet.

---

.azure-pipelines/generation-pipeline.yml

Follow up to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1257
Fixes the branch names on checkout

Fix checkout branches

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/typescript-sdk.yml

- Removes the version bump script.
- Adds conventional commits message for code generation PR

chore (TypeScript): Add conventional commit message and remove version bump script

---

.azure-pipelines/generation-templates/capture-openapi.yml

Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/603
and generation failure at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=170457&view=logs&j=c3323695-d032-5e61-7715-15770e0bec45&t=ffe81c7f-bcae-5066-faa7-4e42a6f2e612

fix: pin hidi version for now

---

.azure-pipelines/generation-pipeline.yml
.azure-pipelines/generation-templates/language-generation-kiota.yml
.azure-pipelines/generation-templates/language-generation.yml
scripts/Generate-Github-Token.ps1
scripts/create-pull-request.ps1

Fixes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/1320
Replaces the use of PATs for SDK PR generation for use of a GitHub App.
Example PR at https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2818

ci: generate pull requests using Github application

---

.azure-pipelines/generation-pipeline.yml

ci: removes ruby beta as we never shipped a version

---

.azure-pipelines/generation-pipeline.yml

chore: fix path to beta python ccs
